In [1]:
import pandas as pd
import numpy as np

In [3]:
customers = pd.read_csv("../data/olist_customers_dataset.csv")
orders = pd.read_csv("../data/olist_orders_dataset.csv")
products = pd.read_csv("../data/olist_products_dataset.csv")
payments = pd.read_csv("../data/olist_order_payments_dataset.csv")
reviews = pd.read_csv("../data/olist_order_reviews_dataset.csv")
items = pd.read_csv("../data/olist_order_items_dataset.csv")
sellers = pd.read_csv("../data/olist_sellers_dataset.csv")

In [4]:
customers_clean = customers.copy()
orders_clean = orders.copy()
products_clean = products.copy()
payments_clean = payments.copy()
reviews_clean = reviews.copy()
items_clean = items.copy()
sellers_clean = sellers.copy()

In [5]:
# Check missing values again
products_clean.isnull().sum()

product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

In [6]:
# Replace missing categories with Unknown
products_clean["product_category_name"] = (
    products_clean["product_category_name"]
    .fillna("Unknown")
)

In [7]:
# Verify category missing values
products_clean["product_category_name"].isnull().sum()

np.int64(0)

In [8]:
# Count each order status
orders_clean["order_status"].value_counts()

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

In [9]:
# Show cancelled orders
orders_clean[
    orders_clean["order_status"] == "canceled"
].head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
397,1b9ecfe83cdc259250e1a8aca174f0ad,6d6b50b66d79f80827b6d96751528d30,canceled,2018-08-04 14:29:27,2018-08-07 04:10:26,NaN,NaN,2018-08-14 00:00:00
613,714fb133a6730ab81fa1d3c1b2007291,e3fe72696c4713d64d3c10afe71e75ed,canceled,2018-01-26 21:34:08,2018-01-26 21:58:39,2018-01-29 22:33:25,NaN,2018-02-22 00:00:00
1058,3a129877493c8189c59c60eb71d97c29,0913cdce793684e52bbfac69d87e91fd,canceled,2018-01-25 13:34:24,2018-01-25 13:50:20,2018-01-26 21:42:18,NaN,2018-02-23 00:00:00
1130,00b1cb0320190ca0daa2c88b35206009,3532ba38a3fd242259a514ac2b6ae6b6,canceled,2018-08-28 15:26:39,NaN,NaN,NaN,2018-09-12 00:00:00
1801,ed3efbd3a87bea76c2812c66a0b32219,191984a8ba4cbb2145acb4fe35b69664,canceled,2018-09-20 13:54:16,NaN,NaN,NaN,2018-10-17 00:00:00

In [ ]:
# Convert order dates to datetime
orders_clean["order_purchase_timestamp"] = pd.to_datetime(
    orders_clean["order_purchase_timestamp"]
)

orders_clean["order_approved_at"] = pd.to_datetime(
    orders_clean["order_approved_at"]
)

orders_clean["order_delivered_customer_date"] = pd.to_datetime(
    orders_clean["order_delivered_customer_date"]
)

orders_clean["order_estimated_delivery_date"] = pd.to_datetime(
    orders_clean["order_estimated_delivery_date"]
)

In [11]:
# Verify data types
orders_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  str
 1   customer_id                    99441 non-null  str
 2   order_status                   99441 non-null  str
 3   order_purchase_timestamp       99441 non-null  datetime64[us]
 4   order_approved_at              99281 non-null  datetime64[us]
 5   order_delivered_carrier_date   97658 non-null  str
 6   order_delivered_customer_date  96476 non-null  datetime64[us]
 7   order_estimated_delivery_date  99441 non-null  datetime64[us]
dtypes: datetime64[us](4), str(4)
memory usage: 6.1 MB

In [12]:
# Extract purchase year
orders_clean["purchase_year"] = (
    orders_clean["order_purchase_timestamp"].dt.year
)

In [13]:
# Extract purchase month
orders_clean["purchase_month"] = (
    orders_clean["order_purchase_timestamp"].dt.month
)

In [14]:
# Extract month name
orders_clean["month_name"] = (
    orders_clean["order_purchase_timestamp"].dt.month_name()
)

In [15]:
orders_clean[
    ["purchase_year", "purchase_month", "month_name"]
].head()

   purchase_year  purchase_month month_name
0           2017              10    October
1           2018               7       July
2           2018               8     August
3           2017              11   November
4           2018               2   February

In [16]:
# Calculate delivery days
orders_clean["delivery_days"] = (
    orders_clean["order_delivered_customer_date"]
    - orders_clean["order_purchase_timestamp"]
).dt.days

In [17]:
orders_clean["delivery_days"].describe()

count    96476.000000
mean        12.094086
std          9.551746
min          0.000000
25%          6.000000
50%         10.000000
75%         15.000000
max        209.000000
Name: delivery_days, dtype: float64

In [18]:
# Save cleaned datasets

customers_clean.to_csv(
    "../data/cleaned/customers_clean.csv",
    index=False
)

orders_clean.to_csv(
    "../data/cleaned/orders_clean.csv",
    index=False
)

products_clean.to_csv(
    "../data/cleaned/products_clean.csv",
    index=False
)

print("Cleaned files saved successfully")

Cleaned files saved successfully